name: Docker

on:
  schedule:
    - cron: '20 14 * * *'
  push:
    branches: [ "main" ]
    tags:
      - 'docker-v*.*.*'  # Triggers only on tags like docker-v1.0.0

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Release Version from Tag
        id: extract_version
        run: |
          version=${GITHUB_REF##*/}
          version=${version#docker-v}
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: Show Release Version
        run: echo "Version is ${{ steps.extract_version.outputs.version }}"

      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09 # v5.0.0
        with:
          context: ./ros-express-backend
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ghcr.io/${{ env.IMAGE_NAME }}:${{ steps.extract_version.outputs.version }}
            ghcr.io/${{ env.IMAGE_NAME }}:latest